name: Test Java Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('Java/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      run: mvn -B clean test

  record:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Report using hard-coded name (use for dedicated branches)
      run: curl -X GET https://push-counter.herokuapp.com/record/hard-coded-name?build=green 

    - name: Report using branch name (use for a pair on each branch)
      run: |
        export BRANCH=$(git symbolic-ref --short HEAD)
        curl -X GET https://push-counter.herokuapp.com/record/branch-$BRANCH?build=green 

    - name: Report using team name (use for a pair on each branch, need to set the name first)
      run: |
        if [ -f team_name.txt ]; then
            export TEAM=$(head -n 1 team_name.txt)
        else 
            export TEAM=unknown
        fi
        export TEAM=$(head -n 1 team_name.txt)
        curl -X GET https://push-counter.herokuapp.com/record/team-$TEAM?build=green 

    - name: Report using user name of last commit (use for pairs on same branch)
      run: |
        curl -X GET https://push-counter.herokuapp.com/record/user-$GITHUB_ACTOR?build=green 
